# Generated by Django 4.2 on 2023-04-19 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_game', models.CharField(max_length=30)),
                ('game_type', models.CharField(max_length=80)),
                ('title', models.CharField(max_length=15)),
                ('game_description', models.CharField(max_length=120)),
                ('game_note', models.CharField(max_length=15)),
            ],
        ),
    ]
