# Generated by Django 4.2 on 2023-04-20 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Games', '0002_remove_post_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='name_game',
            new_name='game_name',
        ),
    ]
