# Generated by Django 4.2 on 2023-04-21 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Games', '0004_post_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='posts'),
        ),
    ]
