# Generated by Django 4.2 on 2023-04-21 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Games', '0008_dm'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Contact',
            field=models.CharField(default=1, max_length=75),
            preserve_default=False,
        ),
    ]
